/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "202020": "#202020",
        "212529": "#212529",
        "222222": "#222222",
        "282525": "#282525",
        "333333": "#333333",
        "555555": "#555555",
        "666666": "#666666",
        "909090": "#909090",
        "999999": "#999999",
        "swiper": "#007AFF",
        "background-highlight": "#FAFAFA",
        "background-dark": "#A8A8A8",
        "brand-primary": "#0F70F0",
        "brand-hover": "#0C5ECB",
        "brand-white": "#FFFFFF",
        "text-primary": "#212121",
        "text-secondary": "#757575",
        "text-neutral": "#616161",
        "link-primary": "var(--yxt-color-brand-primary)",
        "borders": "#DCDCDC",
        "error": "#940000",
        "yxt-searchbar-form-background": "#FFFFFF",
        "yxt-searchbar-form-outline-base": "var(--yxt-color-borders)",
        "yxt-searchbar-text": "var(--yxt-color-text-primary)",
        "yxt-searchbar-button-background-base": "#FFFFFF",
        "yxt-searchbar-button-background-hover": "#E9E9E9",
        "yxt-searchbar-button-background-active": "var(--yxt-searchbar-button-background-color-base)",
        "yxt-searchbar-button-text-base": "var(--yxt-color-text-primary)",
        "yxt-searchbar-button-text-active": "var(--yxt-searchbar-button-text-color-base)",
        "yxt-nav-text": "var(--yxt-color-text-primary)",
        "yxt-nav-text-hover": "#C5CACE",
        "yxt-nav-text-active": "var(--yxt-color-brand-primary)",
        "yxt-nav-text-focus-background": "#E9E9E9",
        "yxt-nav-dropdown": "var(--yxt-nav-text-color)",
        "yxt-nav-dropdown-hover": "var(--yxt-nav-dropdown-color)",
        "yxt-nav-dropdown-hover-background": "#EEEFF0",
        "yxt-nav-border": "var(--yxt-color-borders)",
        "yxt-direct-answer-title-background": "var(--yxt-color-brand-primary)",
        "yxt-direct-answer-content-background": "#FFFFFF",
        "yxt-direct-answer-footer-background": "var(--yxt-color-background-highlight)",
        "yxt-direct-answer-title": "#FFFFFF",
        "yxt-direct-answer-content": "var(--yxt-color-text-primary)",
        "yxt-direct-answer-footer": "var(--yxt-color-text-secondary)",
        "yxt-results-title-bar-background": "var(--yxt-color-background-highlight)",
        "yxt-results-filters-background": "#FFFFFF",
        "yxt-results-view-more-background": "var(--yxt-color-background-highlight)",
        "yxt-results-title-bar-text": "var(--yxt-color-text-primary)",
        "yxt-results-filters-text": "var(--yxt-color-text-primary)",
        "yxt-autocomplete-background": "#FFFFFF",
        "yxt-autocomplete-selected-background": "#F9F9F9",
        "yxt-autocomplete-option-hover-background": "#F9F9F9",
        "yxt-autocomplete-separator": "var(--yxt-color-borders)",
        "yxt-autocomplete-text": "var(--yxt-color-text-primary)",
        "yxt-accordion-result-background": "#FFFFFF",
        "yxt-accordion-result-hover": "var(--yxt-color-background-highlight)",
        "yxt-accordion-result-title": "var(--yxt-color-brand-primary)",
        "yxt-accordion-result-details": "var(--yxt-color-text-primary)",
        "yxt-spellCheck-text": "var(--yxt-color-text-primary)",
        "yxt-pagination-text": "var(--yxt-color-text-neutral)",
        "yxt-pagination-text-hover": "var(--yxt-color-brand-white)",
        "yxt-pagination-active-page": "var(--yxt-color-borders)",
        "yxt-pagination-hover": "var(--yxt-color-text-secondary)",
        "yxt-locationBias-text": "var(--yxt-color-text-secondary)",
        "yxt-locationBias-bullet-default": "var(--yxt-locationbias-text-color)",
        "yxt-filter-options-checkmark": "#0F70F0",
        "yxt-filter-options-checkbox-focus": "#000000",
        "yxt-question-submission": "var(--yxt-color-text-primary)",
        "yxt-question-submission-title": "var(--yxt-color-text-primary)",
        "yxt-question-submission-title-bar-background": "var(--yxt-color-background-highlight)",
        "yxt-question-submission-description": "var(--yxt-color-text-primary)",
        "yxt-question-submission-label": "var(--yxt-color-text-primary)",
        "yxt-question-submission-input": "var(--yxt-color-text-primary)",
        "yxt-question-submission-inputError": "var(--yxt-color-error)",
        "yxt-question-submission-formSubmitError": "var(--yxt-color-error)",
        "yxt-question-submission-acknowledgement-bar-bg": "var(--yxt-color-background-highlight)",
        "yxt-standard-card-link": "var(--yxt-color-brand-primary)",
        "yxt-standard-card-subtitle": "var(--yxt-color-text-secondary)",
        "yxt-standard-card-link-hover": "var(--yxt-color-brand-hover)",
        "yxt-result-background": "#FFFFFF",
        "yxt-result-event-background": "var(--yxt-color-background-highlight)",
        "yxt-result-day": "var(--yxt-color-text-primary)",
        "yxt-result-month": "var(--yxt-color-text-primary)",
        "yxt-result-ordinal-background": "var(--yxt-color-brand-primary)",
        "yxt-result-ordinal": "#FFFFFF",
        "yxt-result-details": "var(--yxt-color-text-primary)",
        "yxt-result-title": "var(--yxt-color-text-primary)",
        "yxt-result-subtitle": "var(--yxt-color-text-secondary)",
        "yxt-result-cta": "var(--yxt-color-link-primary)",
        "yxt-accordion-card-cta": "var(--yxt-color-brand-primary)",
        "yxt-accordion-card-background": "#FFFFFF",
        "yxt-accordion-card-content-background": "#FFFFFF",
        "yxt-accordion-card-title": "var(--yxt-color-brand-primary)",
        "yxt-accordion-card-title-hover": "var(--yxt-color-background-highlight)",
        "yxt-accordion-card-subtitle": "var(--yxt-color-text-secondary)",
        "yxt-accordion-card-details": "var(--yxt-color-text-primary)",
        "yxt-results-header": "var(--yxt-color-text-secondary)",
        "yxt-results-header-count": "var(--yxt-color-text-secondary)",
        "yxt-results-header-filters": "var(--yxt-color-text-secondary)",
        "yxt-results-header-universal-background": "var(--yxt-color-brand-white)",
        "1d1914": "#1D1914",
        "2020e0": "#2020E0",
        "4c4c4c": "#4C4C4C",
        "6b7280": "#6B7280",
        "a0a0a0": "#A0A0A0",
        "ababab": "#ABABAB",
        "adb5bd": "#ADB5BD",
        "b2b2b2": "#B2B2B2",
        "cccccc": "#CCCCCC",
        "d1d1d1": "#D1D1D1",
        "dddddd": "#DDDDDD",
        "e20613": "#E20613",
        "e4e4e4": "#E4E4E4",
        "e7e7e7": "#E7E7E7",
        "e9ecef": "#E9ECEF",
        "f5f2f2": "#F5F2F2",
        "ff0000": "#FF0000"
      },
      fontFamily: {
        "body": [
          "UniversLTPro-45Light",
          "sans-serif"
        ],
        "heading": [
          "UniversLTPro-45Light",
          "sans-serif"
        ],
        "arial": [
          "Arial",
          "sans-serif"
        ],
        "helvetica": [
          "Helvetica",
          "sans-serif"
        ],
        "universltpro-45light": [
          "UniversLTPro-45Light",
          "sans-serif"
        ],
        "universltpro-55roman": [
          "UniversLTPro-55Roman",
          "sans-serif"
        ],
        "universltw02-55roman": [
          "UniversLTW02-55Roman",
          "sans-serif"
        ],
        "universltw02-65bold": [
          "UniversLTW02-65Bold",
          "sans-serif"
        ],
        "verdana": [
          "Verdana",
          "sans-serif"
        ],
        "ui-sans-serif": [
          "ui-sans-serif",
          "sans-serif"
        ]
      },
    },
  },
  plugins: [],
}
